### ISSUE TITLE
0.4.1 not building with node 4.2.4 on Debian Jessie

### ISSUE THREAD

**Issue by Shulin** [redis/hiredis-node#112]
I'm trying to build a project containing hiredis on Debian Jessie and node 4.2.4 with Jenkins, but I am running into an issue at during: node-gyp rebuild.  I've attached the important parts of the npm-debug.log file (Everything above what was entered here was just 'silly' or 'verbose' logs that don't matter.):
```
21056 warn In read-all-stream@3.0.1 replacing bundled version of pinkie-promise with pinkie-promise@1.0.0
21057 warn In read-all-stream@3.0.1 replacing bundled version of pinkie with pinkie@1.0.0
21058 warn In got@3.3.1 replacing bundled version of object-assign with object-assign@3.0.0
21059 warn In configstore@0.3.2 replacing bundled version of graceful-fs with graceful-fs@3.0.8
21060 warn In form-data@0.1.2 replacing bundled version of async with async@0.2.10
21061 warn In rimraf@2.5.1 replacing bundled version of glob with glob@6.0.4
21062 warn In touch@0.0.4 replacing bundled version of nopt with nopt@1.0.10
21063 warn In mv@2.1.1 replacing bundled version of rimraf with rimraf@2.4.5
21064 warn In mv@2.1.1 replacing bundled version of glob with glob@6.0.4
21065 warn In rc@1.1.6 replacing bundled version of minimist with minimist@1.2.0
21066 warn In bunyan@1.5.1 replacing bundled version of dtrace-provider with dtrace-provider@0.6.0
21067 warn In burrito@0.2.12 replacing bundled version of traverse with traverse@0.5.2
21068 warn In request@2.67.0 replacing bundled version of combined-stream with combined-stream@1.0.5
21069 warn In request@2.67.0 replacing bundled version of form-data with form-data@1.0.0-rc3
21070 warn In request@2.67.0 replacing bundled version of delayed-stream with delayed-stream@1.0.0
21071 warn In request@2.67.0 replacing bundled version of async with async@1.5.2
21072 warn In restify@2.8.4 replacing bundled version of assert-plus with assert-plus@0.1.5
21073 warn In restify@2.8.4 replacing bundled version of http-signature with http-signature@0.10.1
21074 warn In restify@2.8.4 replacing bundled version of qs with qs@1.2.2
21075 warn In restify@2.8.4 replacing bundled version of verror with verror@1.6.0
21076 warn In restify@2.8.4 replacing bundled version of deep-equal with deep-equal@0.2.2
21077 warn In restify@2.8.4 replacing bundled version of semver with semver@2.3.2
21078 warn In restify@2.8.4 replacing bundled version of asn1 with asn1@0.1.11
21079 warn In restify@2.8.4 replacing bundled version of extsprintf with extsprintf@1.2.0
21080 warn In nodemon@1.3.7 replacing bundled version of minimatch with minimatch@0.3.0
21081 warn In ioredis@1.14.0 replacing bundled version of lodash with lodash@3.10.1
21082 warn In dtrace-provider@0.3.2 replacing bundled version of nan with nan@1.3.0
21083 warn In node-gyp@3.1.0 replacing bundled version of minimatch with minimatch@1.0.0
21084 verbose stack Error: hiredis@0.4.1 install: `node-gyp rebuild`
21084 verbose stack Exit status 1
21084 verbose stack     at EventEmitter.<anonymous> (/usr/local/nodejs-v4.2.4-54/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
21084 verbose stack     at emitTwo (events.js:87:13)
21084 verbose stack     at EventEmitter.emit (events.js:172:7)
21084 verbose stack     at ChildProcess.<anonymous> (/usr/local/nodejs-v4.2.4-54/lib/node_modules/npm/lib/utils/spawn.js:24:14)
21084 verbose stack     at emitTwo (events.js:87:13)
21084 verbose stack     at ChildProcess.emit (events.js:172:7)
21084 verbose stack     at maybeClose (internal/child_process.js:818:16)
21084 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
21085 verbose pkgid hiredis@0.4.1
21086 verbose cwd /var/lib/jenkins/workspace/myproject/label/jessie/src/libs
21087 error Linux 4.1.0-0.bpo.2-amd64
21088 error argv "/usr/local/nodejs-v4.2.4-54/bin/node" "/usr/local/nodejs-v4.2.4/bin/npm" "install" "--msvs_version=2015"
21089 error node v4.2.4
21090 error npm  v3.5.0
21091 error code ELIFECYCLE
21092 error hiredis@0.4.1 install: `node-gyp rebuild`
21092 error Exit status 1
21093 error Failed at the hiredis@0.4.1 install script 'node-gyp rebuild'.
21093 error Make sure you have the latest version of node.js and npm installed.
21093 error If you do, this is most likely a problem with the hiredis package,
21093 error not with npm itself.
21093 error Tell the author that this fails on your system:
21093 error     node-gyp rebuild
21093 error You can get their info via:
21093 error     npm owner ls hiredis
21093 error There is likely additional logging output above.
21094 verbose exit [ 1, true ]
```

I did see the call out of Linux 4.1.0-0.bpo.2-amd64, and decided to google that and saw a project on GH that had a fix for their project and had this commit message:
`
Debian includes fake Grsecurity patch indistinguishable from the real
one. Bad Debian.
`
Project Commit Fix: https://github.com/aabc/ipt-netflow/commit/bc63dac8cb6ac73d180c76d1cc8c5848892f39ca

But I'm pretty sure that's irrelevant here.

I also noticed the setting of --msvs_version=2015, which is a little suspicious to me as well.

I'm not really sure if this is an issue with my Jenkins setup, or hiredis, or what. Any help/ideas?

**Comment by badboy** [comment]
Can you upload the full logs (silly or verbose). The above log does not include much to act on (except the weird included `--msvs_version`, no idea where that is coming from though)

**Comment by badboy** [comment]
Oh.

```
21088 error argv "/usr/local/nodejs-v4.2.4-54/bin/node" "/usr/local/nodejs-v4.2.4/bin/npm" "install" "--msvs_version=2015"
```

This is the actual argv, means the thing that got executed. So neither node nor npm added that `msvs_version`, but whatever launched it initially did it. You should check your installation method again and make sure to not do that on Linux machines.
