### ISSUE TITLE
Hiredis cann`t install on CenOS

### ISSUE THREAD

**Issue by Ohar** [redis/hiredis-node#124]
I trying to install project with **hiredis 0.5.0** on CentOS and get an errors.
Here is [npm-debug.log.txt](https://github.com/redis/hiredis-node/files/354811/npm-debug.log.txt)

I am using **node 6.2.2** with **nvm**.

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> dtrace-provider@0.2.8 install /opt/redmine/iredmine-api/node_modules/dtrace-provider
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.2.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/redmine/iredmine-api/node_modules/dtrace-provider/.node-gyp"
make: Entering directory `/opt/redmine/iredmine-api/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/opt/redmine/iredmine-api/node_modules/dtrace-provider/build'

> dtrace-provider@0.6.0 install /opt/redmine/iredmine-api/node_modules/ldapjs/node_modules/dtrace-provider
> node scripts/install.js


> hiredis@0.5.0 install /opt/redmine/iredmine-api/node_modules/hiredis
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.2.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp"
make: Entering directory `/opt/redmine/iredmine-api/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
In file included from ../src/reader.h:1,
                 from ../src/hiredis.cc:1:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../src/reader.h:1,
                 from ../src/hiredis.cc:1:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:341: error: expected unqualified-id before ‘using’
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:358: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:365: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:437: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: At global scope:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:477: error: expected unqualified-id before ‘using’
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:809: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:834: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:846: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: At global scope:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:871: error: expected unqualified-id before ‘using’
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:1108: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:1114: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:3246: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: At global scope:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:4463: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:4479: error: ‘nullptr’ was not declared in this scope
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/opt/redmine/iredmine-api/node_modules/hiredis/.node-gyp/6.2.2/include/node/v8.h:7348: error: ‘nullptr’ was not declared in this scope
In file included from ../../nan/nan.h:190,
                 from ../src/reader.h:1,
                 from ../src/hiredis.cc:1:
../../nan/nan_maybe_43_inl.h: At global scope:
../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:59: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:64: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:69: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:76: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:83: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:91: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:98: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:108: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:114: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:118: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:130: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:135: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:139: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:145: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:150: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:156: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:162: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:168: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:174: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:180: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:201: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:205: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:209: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:213: error: expected initializer before ‘<’ token
../../nan/nan_maybe_43_inl.h:217: error: expected initializer before ‘<’ token
../src/hiredis.cc:10: error: expected ‘}’ at end of input
../../nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
make: Leaving directory `/opt/redmine/iredmine-api/node_modules/hiredis/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/p.lysenko/.nvm/v6.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/home/p.lysenko/.nvm/v6.2.2/bin/node" "/home/p.lysenko/.nvm/v6.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/redmine/iredmine-api/node_modules/hiredis
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/opt/redmine/iredmine-api
├─┬ body-parser@1.15.2
│ ├── bytes@2.4.0
│ ├── content-type@1.0.2
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.1.0
│ ├─┬ http-errors@1.5.0
│ │ ├── inherits@2.0.1
│ │ ├── setprototypeof@1.0.1
│ │ └── statuses@1.3.0
│ ├── iconv-lite@0.4.13
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.2.0
│ ├─┬ raw-body@2.1.7
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.13
│   └── media-typer@0.3.0
├─┬ chai@3.5.0
│ ├── assertion-error@1.0.2
│ ├─┬ deep-eql@0.1.3
│ │ └── type-detect@0.1.1
│ └── type-detect@1.0.0
├─┬ express@4.14.0
│ ├─┬ accepts@1.3.3
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├── finalhandler@0.5.0
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.2
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.1.1
│ ├── range-parser@1.2.0
│ ├─┬ send@0.14.1
│ │ ├── destroy@1.0.4
│ │ └── mime@1.3.4
│ ├── serve-static@1.11.1
│ ├── utils-merge@1.0.0
│ └── vary@1.1.0
├─┬ forever@0.15.2
│ ├─┬ cliff@0.1.10
│ │ ├── colors@1.0.3
│ │ └── eyes@0.1.8
│ ├── clone@1.0.2
│ ├── colors@0.6.2
│ ├─┬ flatiron@0.4.3
│ │ ├─┬ broadway@0.3.6
│ │ │ ├── cliff@0.1.9
│ │ │ └── winston@0.8.0
│ │ ├── director@1.2.7
│ │ ├── optimist@0.6.0
│ │ └─┬ prompt@0.2.14
│ │   ├─┬ read@1.0.7
│ │   │ └── mute-stream@0.0.6
│ │   └── revalidator@0.1.8
│ ├─┬ forever-monitor@1.6.0
│ │ ├─┬ chokidar@1.6.0
│ │ │ ├─┬ anymatch@1.3.0
│ │ │ │ ├── arrify@1.0.1
│ │ │ │ └─┬ micromatch@2.3.10
│ │ │ │   ├─┬ arr-diff@2.0.0
│ │ │ │   │ └── arr-flatten@1.0.1
│ │ │ │   ├── array-unique@0.2.1
│ │ │ │   ├─┬ braces@1.8.5
│ │ │ │   │ ├─┬ expand-range@1.8.2
│ │ │ │   │ │ └─┬ fill-range@2.2.3
│ │ │ │   │ │   ├── is-number@2.1.0
│ │ │ │   │ │   ├── isobject@2.1.0
│ │ │ │   │ │   ├── randomatic@1.1.5
│ │ │ │   │ │   └── repeat-string@1.5.4
│ │ │ │   │ ├── preserve@0.2.0
│ │ │ │   │ └── repeat-element@1.1.2
│ │ │ │   ├─┬ expand-brackets@0.1.5
│ │ │ │   │ └── is-posix-bracket@0.1.1
│ │ │ │   ├── extglob@0.3.2
│ │ │ │   ├── filename-regex@2.0.0
│ │ │ │   ├─┬ kind-of@3.0.3
│ │ │ │   │ └── is-buffer@1.1.3
│ │ │ │   ├── normalize-path@2.0.1
│ │ │ │   ├─┬ object.omit@2.0.0
│ │ │ │   │ ├─┬ for-own@0.1.4
│ │ │ │   │ │ └── for-in@0.1.5
│ │ │ │   │ └── is-extendable@0.1.1
│ │ │ │   ├─┬ parse-glob@3.0.4
│ │ │ │   │ ├── glob-base@0.3.0
│ │ │ │   │ └── is-dotfile@1.0.2
│ │ │ │   └─┬ regex-cache@0.4.3
│ │ │ │     ├── is-equal-shallow@0.1.3
│ │ │ │     └── is-primitive@2.0.0
│ │ │ ├── async-each@1.0.0
│ │ │ ├── glob-parent@2.0.0
│ │ │ ├─┬ is-binary-path@1.0.1
│ │ │ │ └── binary-extensions@1.5.0
│ │ │ ├─┬ is-glob@2.0.1
│ │ │ │ └── is-extglob@1.0.0
│ │ │ └─┬ readdirp@2.1.0
│ │ │   ├── graceful-fs@4.1.4
│ │ │   ├── minimatch@3.0.2
│ │ │   ├─┬ readable-stream@2.1.4
│ │ │   │ └── buffer-shims@1.0.0
│ │ │   └── set-immediate-shim@1.0.1
│ │ ├─┬ minimatch@2.0.10
│ │ │ └─┬ brace-expansion@1.1.5
│ │ │   ├── balanced-match@0.4.1
│ │ │   └── concat-map@0.0.1
│ │ └─┬ ps-tree@0.0.3
│ │   └─┬ event-stream@0.5.3
│ │     └── optimist@0.2.8
│ ├─┬ nconf@0.6.9
│ │ ├── async@0.2.9
│ │ ├── ini@1.3.4
│ │ └── optimist@0.6.0
│ ├─┬ nssocket@0.5.3
│ │ ├── eventemitter2@0.4.14
│ │ └── lazy@1.0.11
│ ├── object-assign@3.0.0
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ ├── path-is-absolute@1.0.0
│ ├─┬ prettyjson@1.1.3
│ │ ├── colors@1.1.2
│ │ └── minimist@1.2.0
│ ├─┬ shush@1.0.0
│ │ ├─┬ caller@0.0.1
│ │ │ └─┬ tape@2.3.3
│ │ │   ├── deep-equal@0.1.2
│ │ │   ├── defined@0.0.0
│ │ │   ├── jsonify@0.0.0
│ │ │   ├── resumer@0.0.0
│ │ │   └── through@2.3.8
│ │ └── strip-json-comments@0.1.3
│ ├── timespan@2.3.0
│ ├─┬ utile@0.2.1
│ │ ├── async@0.2.10
│ │ ├── deep-equal@1.0.1
│ │ ├── i@0.3.5
│ │ ├── ncp@0.4.2
│ │ └─┬ rimraf@2.5.3
│ │   └─┬ glob@7.0.5
│ │     ├── fs.realpath@1.0.0
│ │     ├── inflight@1.0.5
│ │     └── once@1.3.3
│ └─┬ winston@0.8.3
│   ├── cycle@1.0.3
│   ├── pkginfo@0.3.1
│   └── stack-trace@0.0.9
├── js-sha512@0.2.2
├─┬ ldap-verifyuser@1.0.2  (git+https://github.com/Ohar/ldap-verifyuser.git#dcff400e2c22dfe7b5a0971452115a64e21b4b4e)
│ └─┬ ldapjs-hotfix@0.7.3
│   ├── asn1@0.2.1
│   ├─┬ bunyan@0.22.1
│   │ └── mv@0.0.5
│   ├── dtrace-provider@0.2.8
│   ├─┬ nopt@2.1.1
│   │ └── abbrev@1.0.9
│   └─┬ pooling@0.4.6
│     ├── once@1.3.0
│     └─┬ vasync@1.4.0
│       ├─┬ jsprim@0.3.0
│       │ ├── extsprintf@1.0.0
│       │ └── verror@1.3.3
│       └── verror@1.1.0
├─┬ ldapjs@1.0.0
│ ├── asn1@0.2.3
│ ├── assert-plus@0.1.5
│ ├─┬ backoff@2.4.1
│ │ └── precond@0.2.3
│ ├─┬ bunyan@1.5.1
│ │ ├─┬ mv@2.1.1
│ │ │ ├── ncp@2.0.0
│ │ │ └─┬ rimraf@2.4.5
│ │ │   └── glob@6.0.4
│ │ └── safe-json-stringify@1.0.3
│ ├── dashdash@1.10.1
│ ├─┬ dtrace-provider@0.6.0
│ │ └── nan@2.3.5
│ ├── ldap-filter@0.2.2
│ ├─┬ once@1.3.2
│ │ └── wrappy@1.0.2
│ ├── vasync@1.6.3
│ └─┬ verror@1.6.0
│   └── extsprintf@1.2.0
├── lodash@4.13.1
├─┬ log4js@0.6.37
│ ├─┬ readable-stream@1.0.34
│ │ ├── core-util-is@1.0.2
│ │ ├── isarray@0.0.1
│ │ └── string_decoder@0.10.31
│ └── semver@4.3.6
├─┬ mocha@2.5.3
│ ├── commander@2.3.0
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.11
│ │ └─┬ minimatch@0.3.0
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.9.2
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── supports-color@1.2.0
│ └── to-iso-string@0.0.2
├── moment@2.14.1
├─┬ mysql@2.11.1
│ ├── bignumber.js@2.3.0
│ ├─┬ readable-stream@1.1.14
│ │ └── isarray@0.0.1
│ └── sqlstring@2.0.1
├── mysql-query@1.1.0
├─┬ redis@2.6.2
│ ├── double-ended-queue@2.1.0-0
│ ├── redis-commands@1.2.0
│ └── redis-parser@2.0.3
├─┬ request@2.72.0
│ ├── aws-sign2@0.6.0
│ ├── aws4@1.4.1
│ ├─┬ bl@1.1.2
│ │ └─┬ readable-stream@2.0.6
│ │   ├── isarray@1.0.0
│ │   ├── process-nextick-args@1.0.7
│ │   └── util-deprecate@1.0.2
│ ├── caseless@0.11.0
│ ├─┬ combined-stream@1.0.5
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.0
│ ├── forever-agent@0.6.1
│ ├─┬ form-data@1.0.0-rc4
│ │ └── async@1.5.2
│ ├─┬ har-validator@2.0.6
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├── strip-ansi@3.0.1
│ │ │ └── supports-color@2.0.0
│ │ ├─┬ commander@2.9.0
│ │ │ └── graceful-readlink@1.0.1
│ │ ├─┬ is-my-json-valid@2.13.1
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ ├── jsonpointer@2.0.0
│ │ │ └── xtend@4.0.1
│ │ └─┬ pinkie-promise@2.0.1
│ │   └── pinkie@2.0.4
│ ├─┬ hawk@3.1.3
│ │ ├── boom@2.10.1
│ │ ├── cryptiles@2.0.5
│ │ ├── hoek@2.16.3
│ │ └── sntp@1.0.9
│ ├─┬ http-signature@1.1.1
│ │ ├── assert-plus@0.2.0
│ │ ├─┬ jsprim@1.3.0
│ │ │ ├── extsprintf@1.0.2
│ │ │ ├── json-schema@0.2.2
│ │ │ └── verror@1.3.6
│ │ └─┬ sshpk@1.8.3
│ │   ├── asn1@0.2.3
│ │   ├── assert-plus@1.0.0
│ │   ├── dashdash@1.14.0
│ │   ├── ecc-jsbn@0.1.1
│ │   ├─┬ getpass@0.1.6
│ │   │ └── assert-plus@1.0.0
│ │   ├── jodid25519@1.0.2
│ │   ├── jsbn@0.1.0
│ │   └── tweetnacl@0.13.3
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.11
│ │ └── mime-db@1.23.0
│ ├── node-uuid@1.4.7
│ ├── oauth-sign@0.8.2
│ ├── qs@6.1.0
│ ├── stringstream@0.0.5
│ ├── tough-cookie@2.2.2
│ └── tunnel-agent@0.4.3
└─┬ socket.io@1.4.8
  ├─┬ engine.io@1.6.11
  │ ├─┬ accepts@1.1.4
  │ │ ├─┬ mime-types@2.0.14
  │ │ │ └── mime-db@1.12.0
  │ │ └── negotiator@0.4.9
  │ ├── base64id@0.1.0
  │ ├─┬ engine.io-parser@1.2.4
  │ │ ├── after@0.8.1
  │ │ ├── arraybuffer.slice@0.0.6
  │ │ ├── base64-arraybuffer@0.1.2
  │ │ ├── blob@0.0.4
  │ │ ├─┬ has-binary@0.1.6
  │ │ │ └── isarray@0.0.1
  │ │ └── utf8@2.1.0
  │ └─┬ ws@1.1.0
  │   ├── options@0.0.6
  │   └── ultron@1.0.2
  ├─┬ has-binary@0.1.7
  │ └── isarray@0.0.1
  ├─┬ socket.io-adapter@0.4.0
  │ └─┬ socket.io-parser@2.2.2
  │   ├── debug@0.7.4
  │   ├── isarray@0.0.1
  │   └── json3@3.2.6
  ├─┬ socket.io-client@1.4.8
  │ ├── backo2@1.0.2
  │ ├── component-bind@1.0.0
  │ ├── component-emitter@1.2.0
  │ ├─┬ engine.io-client@1.6.11
  │ │ ├── component-inherit@0.0.3
  │ │ ├── has-cors@1.1.0
  │ │ ├── parsejson@0.0.1
  │ │ ├── parseqs@0.0.2
  │ │ ├── ws@1.0.1
  │ │ ├── xmlhttprequest-ssl@1.5.1
  │ │ └── yeast@0.1.2
  │ ├── indexof@0.0.1
  │ ├── object-component@0.0.3
  │ ├─┬ parseuri@0.0.4
  │ │ └─┬ better-assert@1.0.2
  │ │   └── callsite@1.0.0
  │ └── to-array@0.1.4
  └─┬ socket.io-parser@2.2.6
    ├── benchmark@1.0.0
    ├── component-emitter@1.1.2
    ├── isarray@0.0.1
    └── json3@3.3.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/home/p.lysenko/.nvm/v6.2.2/bin/node" "/home/p.lysenko/.nvm/v6.2.2/bin/npm" "i"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hiredis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/redmine/iredmine-api/npm-debug.log

```

**Comment by badboy** [comment]
```
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```

Looks like your compiler is too old. You need gcc / g++ 4.8 or newer.
