### ISSUE TITLE
npm install fails for hiredis@0.5.0

### ISSUE THREAD

**Issue by luzianscherrer** [redis/hiredis-node#131]
npm install fails for hiredis@0.5.0:

```
25985 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
25986 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current:
 {"os":"linux","arch":"x64"})
25987 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
25987 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
25987 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
25987 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
25988 verbose stack Error: hiredis@0.5.0 install: `node-gyp rebuild`
25988 verbose stack Exit status 1
25988 verbose stack     at EventEmitter.<anonymous> (/usr/local/soe/software/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
25988 verbose stack     at emitTwo (events.js:106:13)
25988 verbose stack     at EventEmitter.emit (events.js:191:7)
25988 verbose stack     at ChildProcess.<anonymous> (/usr/local/soe/software/lib/node_modules/npm/lib/utils/spawn.js:40:14)
25988 verbose stack     at emitTwo (events.js:106:13)
25988 verbose stack     at ChildProcess.emit (events.js:191:7)
25988 verbose stack     at maybeClose (internal/child_process.js:877:16)
25988 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
25989 verbose pkgid hiredis@0.5.0
25990 verbose cwd /usr/local/soe/software
25991 error Linux 3.0.101-0.47.90-default
25992 error argv "/usr/local/soe/software/bin/node" "/usr/local/soe/software/bin/npm" "--proxy" "http://ktzh.igw.services.zh.ch:8080" 
"--without-ssl" "--insecure" "install"
25993 error node v6.9.5
25994 error npm  v3.10.10
25995 error code ELIFECYCLE
25996 error hiredis@0.5.0 install: `node-gyp rebuild`
25996 error Exit status 1
25997 error Failed at the hiredis@0.5.0 install script 'node-gyp rebuild'.
25997 error Make sure you have the latest version of node.js and npm installed.
25997 error If you do, this is most likely a problem with the hiredis package,
25997 error not with npm itself.
25997 error Tell the author that this fails on your system:
25997 error     node-gyp rebuild
25997 error You can get information on how to open an issue for this project with:
25997 error     npm bugs hiredis
25997 error Or if that isn't available, you can get their info via:
25997 error     npm owner ls hiredis
25997 error There is likely additional logging output above.
25998 verbose exit [ 1, true ]
```

**Comment by badboy** [comment]
Please try again with `npm --loglevel silly ...`, otherwise there's not enough info to act on

**Comment by luzianscherrer** [comment]
...
```
259 info lifecycle hiredis@0.5.0~install: hiredis@0.5.0
260 verbose lifecycle hiredis@0.5.0~install: unsafe-perm in lifecycle false
261 verbose lifecycle hiredis@0.5.0~install: PATH: /usr/local/myapp/software/lib/node_module
s/npm/bin/node-gyp-bin:/usr/local/myapp/software/node_modules/hiredis/node_modules/.bin:/usr
/local/myapp/software/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/s
bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/local/myapp/software/bin/:/usr/local/myapp/software/
node_modules/bunyan/bin:/usr/local/myapp/software/wkhtmltopdf/bin:
262 verbose lifecycle hiredis@0.5.0~install: CWD: /usr/local/myapp/software/node_modules/hir
edis
263 silly lifecycle hiredis@0.5.0~install: Args: [ '-c', 'node-gyp rebuild' ]
264 silly lifecycle hiredis@0.5.0~install: Returned: code: 1  signal: null
265 info lifecycle hiredis@0.5.0~install: Failed to exec install script
266 verbose unlock done using /root/.npm/_locks/staging-eab21d3f8703e805.lock for /usr/loc
al/myapp/software/node_modules/.staging
267 silly rollbackFailedOptional Starting
268 silly rollbackFailedOptional Finishing
269 silly runTopLevelLifecycles Finishing
270 silly install printInstalled
271 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/nod
e_modules/fsevents):
272 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wan
ted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
273 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
273 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
273 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
273 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
274 verbose stack Error: hiredis@0.5.0 install: `node-gyp rebuild`
274 verbose stack Exit status 1
274 verbose stack     at EventEmitter.<anonymous> (/usr/local/myapp/software/lib/node_module
s/npm/lib/utils/lifecycle.js:255:16)
274 verbose stack     at emitTwo (events.js:106:13)
274 verbose stack     at EventEmitter.emit (events.js:191:7)
274 verbose stack     at ChildProcess.<anonymous> (/usr/local/myapp/software/lib/node_module
s/npm/lib/utils/spawn.js:40:14)
274 verbose stack     at emitTwo (events.js:106:13)
274 verbose stack     at ChildProcess.emit (events.js:191:7)
274 verbose stack     at maybeClose (internal/child_process.js:877:16)
274 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:22
6:5)
275 verbose pkgid hiredis@0.5.0
276 verbose cwd /usr/local/myapp/software
277 error Linux 3.0.101-0.47.90-default
278 error argv "/usr/local/myapp/software/bin/node" "/usr/local/myapp/software/bin/npm" "--pro
xy" "http://ktzh.igw.services.zh.ch:8080" "--without-ssl" "--insecure" "--loglevel" "silly
" "install"
279 error node v6.9.5
280 error npm  v3.10.10
281 error code ELIFECYCLE
282 error hiredis@0.5.0 install: `node-gyp rebuild`
282 error Exit status 1
283 error Failed at the hiredis@0.5.0 install script 'node-gyp rebuild'.
283 error Make sure you have the latest version of node.js and npm installed.
283 error If you do, this is most likely a problem with the hiredis package,
283 error not with npm itself.
283 error Tell the author that this fails on your system:
283 error     node-gyp rebuild
283 error You can get information on how to open an issue for this project with:
283 error     npm bugs hiredis
283 error Or if that isn't available, you can get their info via:
283 error     npm owner ls hiredis
283 error There is likely additional logging output above.
284 verbose exit [ 1, true ]
```

**Comment by badboy** [comment]
I still don't see anything obvious. Please make sure you have a working node-gyp install as well as a working compiler toolchain (gcc and required libs). Also make sure your compiler is at least gcc v4.8

**Comment by badboy** [comment]
>  25991 error Linux 3.0.101-0.47.90-default

If this is your kernel version, I urge you to upgrade to a more recent stable kernel and accompanying tools

**Comment by luzianscherrer** [comment]
Thanks, my gcc is currently at 4.3. I'll upgrade the components, you can close the issue.
