### ISSUE TITLE
Does not build on io.js 2.0.0

### ISSUE THREAD

**Issue by johnbona** [redis/hiredis-node#83]
Below is the output for `npm install hiredis` on io.js 2.0.0:

```
\
> hiredis@0.3.0 install /home/user/app/node_modules/hiredis
> node-gyp rebuild

make: Entering directory '/home/user/app/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
In file included from ../node_modules/nan/nan_new.h:181:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/reader.h:4,
                 from ../src/hiredis.cc:3:
../node_modules/nan/nan_implementation_12_inl.h: In static member function 'static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)':
../node_modules/nan/nan_implementation_12_inl.h:172:76: error: no matching function for call to 'v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)'
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:172:76: note: candidate is:
In file included from ../src/hiredis.cc:1:0:
/home/user/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/user/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
hiredis.target.mk:98: recipe for target 'Release/obj.target/hiredis/src/hiredis.o' failed
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
make: Leaving directory '/home/user/app/node_modules/hiredis/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Linux 3.18.7-tinycore64
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/app/node_modules/hiredis
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.18.7-tinycore64
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "hiredis"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/app/npm-debug.log
```

**Comment by inetfuture** [comment]
io.js 2.0.0
osx 10.10.3 (14D136)

```
> hiredis@0.3.0 install /Users/aaron/wp/server/node_modules/hiredis
> node-gyp rebuild

  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  LIBTOOL-STATIC Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:181:
../node_modules/nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/aaron/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aaron/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/aaron/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/aaron/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aaron/wp/server/node_modules/hiredis
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/aaron/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/aaron/.nvm/versions/io.js/v2.0.0/bin/npm" "install" "hiredis"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaron/wp/server/npm-debug.log
```

**Comment by badboy** [comment]
thanks! This needs a nan upgrade. I'll push a release later today.

**Comment by dpatti** [comment]
Would you consider using a less strict semver for nan to prevent things like this in the future? Something like `^1.8.4` would do nicely.

**Comment by badboy** [comment]
See #84

**Comment by heavyk** [comment]
I also vote for `^1.8.4` -- as it's pretty unlikely that future nan releases will break backward compat. it's far more likely that an outdated version of nan won't work with a future version of iojs (than the other way around, I mean)

**Comment by fujifish** [comment]
Any idea when a new version with a fix will be released to npm?

**Comment by badboy** [comment]
Soon™ (when I find the time)

**Comment by freak4pc** [comment]
Any way to help with this? Really stuck with it. 
For now I can use nvm to `nvm use node`, then `npm install` and then go back to iojs but that's pretty tricky ;)

**Comment by gabeio** [comment]
@freak4pc if you want to use iojs just use a version prior to v2

**Comment by badboy** [comment]
Fixed.

**Comment by gabeio** [comment]
@badboy :+1: big thanks!

**Comment by badboy** [comment]
You're very welcome and sorry it took me 3 weeks.

**Comment by gabeio** [comment]
It's quiet already was super busy here too, felt like only a few days.

**Comment by fujifish** [comment]
Thanks! works flawlessly.

**Comment by freak4pc** [comment]
Just updating here that now iojs is at 2.1.0 and this bug is back. Doesn't build.

```
> hiredis@0.3.0 install /Users/freak4pc/Work/DreamDate/DreamDate-API/node_modules/hiredis
> node-gyp rebuild

2015-05-30 05:47:30.206 xcodebuild[1798:15026] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Polychromatic.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  LIBTOOL-STATIC Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
In file included from ../src/hiredis.cc:3:
In file included from ../src/reader.h:4:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:181:
../node_modules/nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have
      4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/freak4pc/.node-gyp/2.1.0/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/freak4pc/.nvm/versions/io.js/v2.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/freak4pc/.nvm/versions/io.js/v2.1.0/bin/iojs" "/Users/freak4pc/.nvm/versions/io.js/v2.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/freak4pc/Work/DreamDate/DreamDate-API/node_modules/hiredis
gyp ERR! node -v v2.1.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/freak4pc/.nvm/versions/io.js/v2.1.0/bin/iojs" "/Users/freak4pc/.nvm/versions/io.js/v2.1.0/bin/npm" "install"
npm ERR! node v2.1.0
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/freak4pc/Work/DreamDate/DreamDate-API/npm-debug.log
```

**Comment by heavyk** [comment]
that's cause it's trying to install 0.3.0

installing 0.4.0 will work

**Comment by freak4pc** [comment]
Thanks that worked :)
