### ISSUE TITLE
hiredis-node fails during compliling

### ISSUE THREAD

**Issue by briancuda** [redis/hiredis-node#90]
I am getting an odd crash out of node when I npm install.  The crash is occuring while building hiredis.  Running under CentOS 6.5, Node v0.12.0.  I cleared out all the cache from node, but have seen no change.  Below is the output 

```
$ npm install
> hiredis@0.2.0 install ./node_modules/hiredis
> node-gyp rebuild

make: Entering directory `./node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis.a
  COPY Release/hiredis.a
cp: cannot stat `Release/obj.target/deps/hiredis.a': No such file or directory
make: *** [Release/hiredis.a] Error 1
make: Leaving directory `./node_modules/hiredis/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.32-431.5.1.el6.x86_64
gyp ERR! command "node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ./node_modules/hiredis
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
 
> dtrace-provider@0.5.0 install ./node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

Binary is fine; exiting
npm ERR! Linux 2.6.32-431.5.1.el6.x86_64
npm ERR! argv "node" "/usr/local/node/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ./npm-debug.log
```

**Comment by badboy** [comment]
I can't reproduce it here on a fresh CentOS machine. Not with hiredis 0.2 and not with the latest release 0.4

Your bug report shows that for some reason it failed to compile the library. Can you please re-run it using `npm --loglevel verbose install`? This should give more info.
Do you have all build tools installed, like `ar`, which probably failed?

**Comment by briancuda** [comment]
Thanks, ar was the problem.  Once I corrected that the problem went away.
