### ISSUE TITLE
Hiredis does not install in Win7 x64 with .NET v4

### ISSUE THREAD

**Issue by Bruce17** [redis/hiredis-node#92]
I'm trying to install hiredis on a Win7 x64 SP1 with .NET framework v4.0.30319.

The installer complains, that the component "VCBuild.exe" couldn't be found. I should do the following stuff:
1) install .NET framework v2 -> **doesn't work**
2) Microsoft Visual Studio 2005 -> **doens'nt work**
3) change the components system path (I don't know what they want from me at this point)

Am I able to to build hiredis with .NET v4? Why do I need to install a ten year old .NET version?

Here is the log:

```bash
npm i --save hiredis --python="c:\Python27"
npm WARN package.json node-module-urm@1.0.0 No license field.
/
> hiredis@0.4.0 install C:\project-path\node_modules\hiredis
> node-gyp rebuild


C:\project-path\node_modules\hiredis>if not defined npm_config_node_gyp (node "C:\Users\mir\AppData\Roaming\nvm\v0.12.5\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0
 SDK oder 2) Microsoft Visual Studio 2005 oder 3) fügen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\Users\mir\
Documents\Projekte\gfk\backend\node-module-urm\node_modules\hiredis\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mir\AppData\Roaming\nvm\v0.12.5\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\mir\\AppData\\Roaming\\nvm\\v0.12.5\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\project-path\node_modules\hiredis
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "hiredis" "--python=c:\\Python27"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\project-path\npm-debug.log
```

**Comment by badboy** [comment]
Sorry, I have absolutely no clue how development on Windows works and rely solely on external input and my best effort to get it working on Windows. I rely on [appveyor](https://ci.appveyor.com/project/badboy/hiredis-node) to run builds. 
You might be able to check their environment to understand how to get it working.

**Comment by Bruce17** [comment]
Thx I will have a look ...
Am 07.07.2015 4:45 nachm. schrieb "Jan-Erik Rediger" <
notifications@github.com>:

**Comment by XVincentX** [comment]
@Bruce17 I do not know if you solved, but I am quite sure that Visual Studio 2005 is not supported by node-gyp tools.

You should at least install mscv 2010

**Comment by Bruce17** [comment]
@XVincentX I've installed mscv 2010, but node-gyp is not able to locate the proper version of mscv

**Comment by badboy** [comment]
Does this help? https://github.com/nodejs/node-gyp/wiki/Visual-Studio-2010-Setup

**Comment by sah2ed** [comment]
Any resolution yet? _hiredis_ still doesn't install on Windows due to its dependency on UNIX-specific headers. Tested on Windows 8.1 with VS 2013 installed.

```
if not defined npm_config_node_gyp (node "C:\Apps\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )                                                                                                                                                                
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.                                                             
  hiredis.c                                                                                                                                                             
  net.c                                                                                                                                                                 
  sds.c                                                                                                                                                                 
  async.c                                                                                                                                                               
..\..\deps\hiredis\net.c(35): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                         
..\..\deps\hiredis\async.c(35): fatal error C1083: Cannot open include file: 'strings.h': No such file or directory [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                          
C:\path\to\node-project\node_modules\hiredis\deps\hiredis\sds.h(45): error C2054: expected '(' to follow 'inline' (..\..\deps\hiredis\sds.c) [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                         
C:\path\to\node-project\node_modules\hiredis\deps\hiredis\sds.h(45): error C2085: 'sdslen' : not in formal parameter list (..\..\deps\hiredis\sds.c) [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                 
C:\path\to\node-project\node_modules\hiredis\deps\hiredis\sds.h(45): error C2143: syntax error : missing ';' before '{' (..\..\deps\hiredis\sds.c) [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                   
C:\path\to\node-project\node_modules\hiredis\deps\hiredis\sds.h(50): error C2054: expected '(' to follow 'inline' (..\..\deps\hiredis\sds.c) [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                         
C:\path\to\node-project\node_modules\hiredis\deps\hiredis\sds.h(50): error C2085: 'sdsavail' : not in formal parameter list (..\..\deps\hiredis\sds.c) [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                               
C:\path\to\node-project\node_modules\hiredis\deps\hiredis\sds.h(50): error C2143: syntax error : missing ';' before '{' (..\..\deps\hiredis\sds.c) [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                   
..\..\deps\hiredis\sds.c(53): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                  
..\..\deps\hiredis\sds.c(83): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                       
..\..\deps\hiredis\sds.c(104): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(122): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(123): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj] 
..\..\deps\hiredis\sds.c(135): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(136): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(157): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(158): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\hiredis.c(35): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                         
..\..\deps\hiredis\sds.c(214): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(215): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(225): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(229): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(237): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(245): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(246): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                                 
..\..\deps\hiredis\sds.c(251): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                      
..\..\deps\hiredis\sds.c(257): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                      
..\..\deps\hiredis\sds.c(270): warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data [C:\path\to\node-project\node_modules\hiredis\build\deps\hiredis.vcxproj]                                                                                                                            
gyp ERR! build error                                                                                                                                                    
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1                                                                    
gyp ERR! stack     at ChildProcess.onExit (C:\Apps\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)                                                   
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)                                                                                                              
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)                                                                                    
gyp ERR! System Windows_NT 6.3.9600                                                                                                                                     
gyp ERR! command "node" "C:\\Apps\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"                                                       
gyp ERR! cwd C:\path\to\node-project\node_modules\hiredis                                                                                       
gyp ERR! node -v v0.12.7                                                                                                                                                
gyp ERR! node-gyp -v v2.0.1                                                                                                                                             
gyp ERR! not ok                                                                                                                                                         
npm ERR! Windows_NT 6.3.9600                                                                                                                                            
npm ERR! argv "C:\\Apps\\nodejs\\\\node.exe" "C:\\Apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "hiredis"                                                 
npm ERR! node v0.12.7                                                                                                                                                   
npm ERR! npm  v2.11.3                                                                                                                                                   
npm ERR! code ELIFECYCLE                                                                                                                                                
                                                                                                                                                                        
npm ERR! hiredis@0.1.17 install: `node-gyp rebuild`                                                                                                                     
npm ERR! Exit status 1                                                                                                                                                  
npm ERR!                                                                                                                                                                
npm ERR! Failed at the hiredis@0.1.17 install script 'node-gyp rebuild'.                                                                                                
npm ERR! This is most likely a problem with the hiredis package,                                                                                                        
npm ERR! not with npm itself.                                                                                                                                           
npm ERR! Tell the author that this fails on your system:                                                                                                                
npm ERR!     node-gyp rebuild                                                                                                                                           
npm ERR! You can get their info via:                                                                                                                                    
npm ERR!     npm owner ls hiredis                                                                                                                                       
npm ERR! There is likely additional logging output above.                                                                                                               
                                                                                                                                                                        
npm ERR! Please include the following file with any support request:                                                                                                    
npm ERR!     C:\path\to\node-project\npm-debug.log                                                                                              
                                                                                                            
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        
```

**Comment by badboy** [comment]
It does [according to the CI](https://ci.appveyor.com/project/badboy/hiredis-node) and that's about the only way I can test that.
We don't have `hiredis.vcxproj` in the project and we explicitely don't use the `net.c` stuff that is *nix-only.
What code are you actually using? It's obviously not this repository and it's not the npm package.

**Comment by sah2ed** [comment]
Sorry, my bad. The project was using an older _hiredis_ version (~0.1.17) in package.json. 
I switched to _hiredis_ 0.4.1 and it works fine now.

Thanks!

**Comment by badboy** [comment]
Perfect! Thanks for the feedback.
