### ISSUE TITLE
Error: No compatible version found: nan@'^2.0.5', node 0.8

### ISSUE THREAD

**Issue by masterkain** [redis/hiredis-node#98]
I'm using a node module `caching`, which in turns requires `hiredis`, but I'm not able to install it anymore, not on my system or production servers.

any advice?

```
$ npm install hiredis

npm http GET https://registry.npmjs.org/hiredis
npm http 304 https://registry.npmjs.org/hiredis
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm ERR! Error: No compatible version found: nan@'^2.0.5'
npm ERR! Valid install targets:
npm ERR! ["0.3.0-wip","0.3.0-wip2","0.3.0","0.3.1","0.3.2","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.5.1","0.5.2","0.6.0","0.7.0","0.7.1","0.8.0","1.0.0","1.1.0","1.1.1","1.1.2","1.2.0","1.3.0","1.4.0","1.4.1","1.5.0","1.4.2","1.4.3","1.5.1","1.5.2","1.6.0","1.5.3","1.6.1","1.6.2","1.7.0","1.8.0","1.8.1","1.8.2","1.8.3","1.8.4","1.9.0","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.0.8"]
npm ERR!     at installTargetsError (/Users/kain/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /Users/kain/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/Users/kain/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/kain/.nvm/v0.8.28/bin/node" "/Users/kain/.nvm/v0.8.28/bin/npm" "install" "hiredis"
```

**Comment by badboy** [comment]
Upgrade your npm (and upgrade your node please).
